version: '3'
services:
  postgres:
    image: postgres:11.6
    hostname: postgres
    environment:
      POSTGRES_USER: postgres # Must be the same as DB_USER below
      POSTGRES_PASSWORD: postgres # Must be the same as DB_PASSWORD below
      POSTGRES_DB: retroboard # Must be the same as DB_NAME below
    volumes:
      - database_old:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  pgadmin:
    image: arnabcse28/pgadmin4:custom
    depends_on:
      - postgres
    ports:
      - '8081:80' # Change 8080 to whatever port you want to access pgAdmin from
    environment:
      PGADMIN_DEFAULT_EMAIL: admin123@retrospected.com # Can be anything
      PGADMIN_DEFAULT_PASSWORD: admin # Please change this!
    volumes:
      - pgadmin_old:/var/lib/pgadmin
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  backend:
    image: arnabcse28/retro-board-backend:2.2.1
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DB_TYPE: postgres
      DB_NAME: retroboard # Must be the same as POSTGRES_DB above
      DB_USER: postgres # Must be the same as POSTGRES_USER above
      DB_PASSWORD: postgres # Must be the same as POSTGRES_PASSWORD above
      DB_HOST: postgres # Must be the name of the Postgres container
      DB_PORT: 5432 # Don't change this.
      BACKEND_PORT: 3201 # Don't change this (or change it in nginx.conf as well)
      SQL_LOG: 'false' # Whether to log SQL queries in the console
      REDIS_ENABLED: 'false' # Whether to enable Redis, only useful in the context of a Kubernetes cluster
      REDIS_PORT: 6379 # Not used by default
      REDIS_HOST: redis # Not used by default
      SENTRY_URL: '' # Optional, Sentry URL (https://1234567890abcdef12345@sentry.io/1234567)
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  frontend:
    image: arnabcse28/retro-board-frontend:2.2.1
    depends_on:
      - backend
    ports:
      - '8082:80' # Change the first 80 to whatever port you want to access Retrospected from
    environment:
      BACKEND_HOST: backend # This should be the name of the backend service
      BACKEND_PORT: 3201 # This should be the same as BACKEND_PORT on backend
      GA_ID: '' # Optional, Google Analytics ID (UA-1234456-7)
      SENTRY_URL: '' # Optional, Sentry URL (https://1234567890abcdef12345@sentry.io/1234567)
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

volumes:
  database_old:
  pgadmin_old: